import { AppState } from "@/types";

export const seedData: AppState = {
  questions: [
    {
      id: "q1",
      text: "Tell me about a time you had to deal with a difficult team member.",
      category: "behavioral",
      practiced: false,
      storyId: null,
      notes: "",
      createdAt: Date.now() - 86400000 * 5,
    },
    {
      id: "q2",
      text: "Describe a situation where you had to make a decision with incomplete information.",
      category: "behavioral",
      practiced: true,
      storyId: "s1",
      notes: "Focus on the framework I used to evaluate options.",
      createdAt: Date.now() - 86400000 * 4,
    },
    {
      id: "q3",
      text: "Walk me through how you would prioritize features for a new product launch.",
      category: "product-case",
      practiced: false,
      storyId: null,
      notes: "",
      createdAt: Date.now() - 86400000 * 3,
    },
    {
      id: "q4",
      text: "How would you measure the success of a new feature?",
      category: "product-case",
      practiced: false,
      storyId: null,
      notes: "",
      createdAt: Date.now() - 86400000 * 2,
    },
    {
      id: "q5",
      text: "Tell me about a time you failed and what you learned from it.",
      category: "behavioral",
      practiced: false,
      storyId: null,
      notes: "",
      createdAt: Date.now() - 86400000,
    },
    {
      id: "q6",
      text: "How do you stay current with industry trends and technologies?",
      category: "role-specific",
      practiced: false,
      storyId: null,
      notes: "",
      createdAt: Date.now(),
    },
    {
      id: "q7",
      text: "Describe your approach to debugging a complex system issue.",
      category: "role-specific",
      practiced: false,
      storyId: null,
      notes: "",
      createdAt: Date.now(),
    },
    {
      id: "q8",
      text: "Tell me about a time you influenced a decision without having authority.",
      category: "behavioral",
      practiced: false,
      storyId: null,
      notes: "",
      createdAt: Date.now(),
    },
  ],

  companies: [
    {
      id: "c1",
      name: "Tandem",
      role: "S&O Lead",
      status: "interviewing" as const,
      interviewDate: "",
      whyCompany: "",
      whyRole: "",
      notes: "",
      questionsAsked: [],
      questionsToAsk: [],
      createdAt: Date.now() - 86400000 * 5,
    },
    {
      id: "c2",
      name: "Mochi Health",
      role: "Operations Associate - Strategy",
      status: "interviewing" as const,
      interviewDate: "",
      whyCompany: "",
      whyRole: "",
      notes: "",
      questionsAsked: [],
      questionsToAsk: [],
      createdAt: Date.now() - 86400000 * 3,
    },
  ],

  checklist: [
    // General prep tasks
    { id: "cl1", text: "Update resume", completed: true, dueDate: "", companyId: null, recurring: null, eventId: null, createdAt: Date.now() - 86400000 * 7 },
    { id: "cl2", text: "Prepare 3 STAR stories", completed: false, dueDate: "2026-04-10", companyId: null, recurring: null, eventId: null, createdAt: Date.now() - 86400000 * 6 },
    { id: "cl3", text: "Practice answering out loud", completed: false, dueDate: "", companyId: null, recurring: null, eventId: null, createdAt: Date.now() - 86400000 * 4 },
    { id: "cl4", text: "Do a mock interview with a friend", completed: false, dueDate: "2026-04-09", companyId: null, recurring: null, eventId: null, createdAt: Date.now() - 86400000 * 2 },
    // Event-specific prep tasks
    { id: "cl8", text: "Why this role?", completed: false, dueDate: "", companyId: null, recurring: null, eventId: "ev2", createdAt: Date.now() - 86400000 },
    { id: "cl9", text: "Why this company?", completed: false, dueDate: "", companyId: null, recurring: null, eventId: "ev2", createdAt: Date.now() - 86400000 },
    { id: "cl10", text: "Why this role?", completed: false, dueDate: "", companyId: null, recurring: null, eventId: "ev3", createdAt: Date.now() - 86400000 },
    { id: "cl11", text: "Why this company?", completed: false, dueDate: "", companyId: null, recurring: null, eventId: "ev3", createdAt: Date.now() - 86400000 },
    { id: "cl12", text: "Why this role?", completed: false, dueDate: "", companyId: null, recurring: null, eventId: "ev6", createdAt: Date.now() - 86400000 },
    { id: "cl13", text: "Why this company?", completed: false, dueDate: "", companyId: null, recurring: null, eventId: "ev6", createdAt: Date.now() - 86400000 },
    { id: "cl14", text: "Why this role?", completed: false, dueDate: "", companyId: null, recurring: null, eventId: "ev7", createdAt: Date.now() - 86400000 },
    { id: "cl15", text: "Why this company?", completed: false, dueDate: "", companyId: null, recurring: null, eventId: "ev7", createdAt: Date.now() - 86400000 },
  ],

  stories: [
    {
      id: "s1",
      title: "Led migration to new data pipeline",
      situation:
        "Our team's data pipeline was outdated and causing frequent outages, affecting downstream analytics for 50+ stakeholders.",
      task: "I was tasked with leading the migration to a new pipeline architecture within a 3-month deadline.",
      action:
        "I mapped all dependencies, created a phased migration plan, set up parallel pipelines for testing, and coordinated with 4 teams to ensure a smooth transition.",
      result:
        "We completed the migration 2 weeks early with zero downtime. Pipeline reliability improved from 94% to 99.8%.",
      tags: ["leadership", "technical", "project-management"],
      feedback: [
        {
          id: "f1",
          text: "Add more detail about how you handled disagreements during the planning phase.",
          resolved: false,
          createdAt: Date.now() - 86400000,
        },
        {
          id: "f2",
          text: "Quantify the cost savings from improved reliability.",
          resolved: true,
          createdAt: Date.now() - 86400000 * 2,
        },
      ],
      createdAt: Date.now() - 86400000 * 5,
      updatedAt: Date.now() - 86400000,
    },
  ],

  events: [
    // Thursday Apr 2
    {
      id: "ev8",
      title: "Tandem — S&O Lead",
      date: "2026-04-02",
      startTime: "14:40",
      endTime: "15:00",
      category: "interview",
      interviewType: "recruiter-screen",
      interviewStage: "recruiter",
      companyId: null,
      companyName: "Tandem",
      role: "S&O Lead",
      questionsAsked: ["TMAY", "What are you looking for in your next role and next company?"],
      questionsToAsk: [],
      notes: "",
      createdAt: Date.now(),
    },
    // Friday Apr 3 (today)
    {
      id: "ev0",
      title: "Mochi Health — Operations Associate - Strategy",
      date: "2026-04-03",
      startTime: "15:20",
      endTime: "15:35",
      category: "interview",
      interviewType: "recruiter-screen",
      interviewStage: "recruiter",
      companyId: null,
      companyName: "Mochi Health",
      role: "Operations Associate - Strategy",
      questionsAsked: [],
      questionsToAsk: [],
      notes: "",
      createdAt: Date.now(),
    },
    // Sunday Apr 5
    {
      id: "ev1",
      title: "Mock interview with Lilian",
      date: "2026-04-05",
      startTime: "11:00",
      endTime: "12:00",
      category: "practice",
      interviewType: "behavioral",
      interviewStage: null,
      companyId: null,
      companyName: "",
      role: "",
      questionsAsked: [],
      questionsToAsk: [],
      notes: "",
      createdAt: Date.now(),
    },
    // Monday Apr 6
    {
      id: "ev2",
      title: "Blink Health — Network Strat & Partner Ops",
      date: "2026-04-06",
      startTime: "10:00",
      endTime: "10:30",
      category: "interview",
      interviewType: "recruiter-screen",
      interviewStage: "recruiter",
      companyId: null,
      companyName: "Blink Health",
      role: "Manager, Network Strat and Partner Operations",
      questionsAsked: [],
      questionsToAsk: [],
      notes: "",
      createdAt: Date.now(),
    },
    {
      id: "ev3",
      title: "Clover Health — Special Projects Lead",
      date: "2026-04-06",
      startTime: "13:00",
      endTime: "13:30",
      category: "interview",
      interviewType: "recruiter-screen",
      interviewStage: "recruiter",
      companyId: null,
      companyName: "Clover Health",
      role: "Special Projects Lead - Office of CEO",
      questionsAsked: [],
      questionsToAsk: [],
      notes: "",
      createdAt: Date.now(),
    },
    {
      id: "ev4",
      title: "Mock interview with Will",
      date: "2026-04-06",
      startTime: "17:00",
      endTime: "18:00",
      category: "practice",
      interviewType: "case",
      interviewStage: null,
      companyId: null,
      companyName: "",
      role: "",
      questionsAsked: [],
      questionsToAsk: [],
      notes: "",
      createdAt: Date.now(),
    },
    // Friday Apr 10
    {
      id: "ev5",
      title: "Mock interview with Paul",
      date: "2026-04-10",
      startTime: "09:00",
      endTime: "10:00",
      category: "practice",
      interviewType: "behavioral",
      interviewStage: null,
      companyId: null,
      companyName: "",
      role: "",
      questionsAsked: [],
      questionsToAsk: [],
      notes: "",
      createdAt: Date.now(),
    },
    {
      id: "ev6",
      title: "Sprinter Health — Clinical Strat Manager",
      date: "2026-04-10",
      startTime: "11:00",
      endTime: "11:30",
      category: "interview",
      interviewType: "recruiter-screen",
      interviewStage: "recruiter",
      companyId: null,
      companyName: "Sprinter Health",
      role: "Clinical Strat Manager",
      questionsAsked: [],
      questionsToAsk: [],
      notes: "",
      createdAt: Date.now(),
    },
    // Monday Apr 13
    {
      id: "ev7",
      title: "Granted — Agent PM",
      date: "2026-04-13",
      startTime: "12:00",
      endTime: "12:30",
      category: "interview",
      interviewType: "recruiter-screen",
      interviewStage: "recruiter",
      companyId: null,
      companyName: "Granted",
      role: "Agent PM",
      questionsAsked: [],
      questionsToAsk: [],
      notes: "",
      createdAt: Date.now(),
    },
  ],

  applications: [
    { id: "a1", company: "Amazon", role: "LDP", appliedDate: "2025-08-17", method: "Company Website", location: "Seattle", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a2", company: "Adobe", role: "Product Manager", appliedDate: "2025-09-05", method: "Company Website", location: "SF, San Jose", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a3", company: "Adobe", role: "Senior GTM Strategy & Execution Manager", appliedDate: "2025-09-05", method: "Company Website", location: "SF, San Jose", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a4", company: "Adobe", role: "PMM", appliedDate: "2025-09-05", method: "Company Website", location: "SF, San Jose", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a5", company: "Adobe", role: "Digital Strategy Associate", appliedDate: "2025-09-05", method: "Company Website", location: "SF, San Jose", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a6", company: "Databricks", role: "Associate Product Manager", appliedDate: "2025-09-05", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a7", company: "Clorox", role: "Associate Marketing Manager", appliedDate: "2025-09-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a8", company: "Medline", role: "Senior Product Manager", appliedDate: "2025-09-12", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a9", company: "Roblox", role: "Associate Product Manager", appliedDate: "2025-09-12", method: "Company Website", location: "", verdict: "Rejected - interviewed", notes: "online assessment", spokeTo: "", createdAt: Date.now() },
    { id: "a10", company: "Experian", role: "LDP", appliedDate: "2025-09-26", method: "Company Website", location: "Remote", verdict: "Rejected - interviewed", notes: "recruiter screen", spokeTo: "", createdAt: Date.now() },
    { id: "a11", company: "Google", role: "Associate Product Manager", appliedDate: "2025-09-26", method: "Company Website", location: "NYC, SF Bay Area", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a12", company: "Oak Street Health", role: "LDP", appliedDate: "2025-09-26", method: "GTS", location: "IL", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a13", company: "Pepsico", role: "Strategic Finance Associate Manager", appliedDate: "2025-09-26", method: "Company Website", location: "LI, NY, TX", verdict: "Withdrew", notes: "Location was changed to Plano, TX", spokeTo: "", createdAt: Date.now() },
    { id: "a14", company: "Uber", role: "Associate Product Manager", appliedDate: "2025-09-26", method: "Company Website", location: "SF", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a15", company: "Adobe", role: "Integrated GTM Associate", appliedDate: "2025-09-27", method: "Company Website", location: "SF, San Jose", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a16", company: "Adobe", role: "Corporate Strategy Manager", appliedDate: "2025-09-27", method: "Company Website", location: "SF, San Jose", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a17", company: "Intuit", role: "Principal Corporate Strategy Manager", appliedDate: "2025-09-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a18", company: "Ramp", role: "Senior PMM", appliedDate: "2025-09-27", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a19", company: "Adobe", role: "Corp Dev Manager", appliedDate: "2025-09-30", method: "Company Website", location: "SF, San Jose", verdict: "Rejected - interviewed", notes: "Round 2", spokeTo: "Matt Cheong - 415-812-8580", createdAt: Date.now() },
    { id: "a20", company: "TikTok", role: "Monetization Strategy & Ops Associate", appliedDate: "2025-10-05", method: "Company Website", location: "NYC", verdict: "No Opening", notes: "", spokeTo: "Jasper Wang - jasper.s.wang@berkeley.edu Frank Chiang - frank.chiang@tiktok.com, 347-225-7557", createdAt: Date.now() },
    { id: "a21", company: "Google", role: "Associate Principal, BizOps & Strategy", appliedDate: "2025-10-11", method: "Company Website", location: "", verdict: "Rejected - interviewed", notes: "online assessment", spokeTo: "", createdAt: Date.now() },
    { id: "a22", company: "Cisco", role: "Corporate Strategy Manager", appliedDate: "2025-10-19", method: "Company Website", location: "SF Bay Area", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a23", company: "TD", role: "LDP", appliedDate: "2025-10-19", method: "Company Website", location: "NYC", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a24", company: "Verkada", role: "Product Manager", appliedDate: "2025-10-19", method: "Company Website", location: "SF Bay Area", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a25", company: "Verkada", role: "Sales S&O", appliedDate: "2025-10-19", method: "Company Website", location: "SF Bay Area", verdict: "Rejected - interviewed", notes: "Round 2", spokeTo: "Ian De Luna - ian.deluna@verkada.com", createdAt: Date.now() },
    { id: "a26", company: "Expedia", role: "Product Manager III", appliedDate: "2025-11-02", method: "Company Website", location: "Seattle", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a27", company: "Hewlett Packard Enterprise", role: "Product Manager", appliedDate: "2025-11-02", method: "Company Website", location: "San Jose, CA", verdict: "Rejected without Interview", notes: "Rejected 3/30", spokeTo: "", createdAt: Date.now() },
    { id: "a28", company: "TikTok", role: "Product Manager", appliedDate: "2025-11-02", method: "Company Website", location: "Seattle", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a29", company: "Microsoft", role: "Business Program Management", appliedDate: "2026-01-06", method: "Company Website", location: "WA", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a30", company: "Canopy Care", role: "Senior PM", appliedDate: "2026-01-15", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a31", company: "CVS", role: "PM, Data Analytics Products Pharma & Life Sciences", appliedDate: "2026-01-15", method: "Company Website", location: "", verdict: "Withdrew", notes: "got first round but too early", spokeTo: "", createdAt: Date.now() },
    { id: "a32", company: "healthee", role: "PM", appliedDate: "2026-01-15", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a33", company: "Journey Clinical", role: "Snior PM", appliedDate: "2026-01-15", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a34", company: "Samsung", role: "Senior Mgr, Product Innovation (metabolic health)", appliedDate: "2026-01-15", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a35", company: "Samsung", role: "Strategy Mgr, Services Biz (Mobile)", appliedDate: "2026-01-15", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a36", company: "Amae Health", role: "S&O", appliedDate: "2026-01-16", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a37", company: "Babylist", role: "CoS to CFO", appliedDate: "2026-01-16", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a38", company: "CVS", role: "Senior Mental Well Being Ops Innovation Mgr", appliedDate: "2026-01-16", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a39", company: "CVS", role: "Sr Mgr Product Ops -CVS CMx", appliedDate: "2026-01-16", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a40", company: "REI", role: "Sr Member Strategist", appliedDate: "2026-01-16", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a41", company: "Scan Health", role: "Growth S&O Mgr", appliedDate: "2026-01-16", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a42", company: "Alma", role: "Ops Mgr, Process Innovation", appliedDate: "2026-01-21", method: "Company Website", location: "", verdict: "Withdrew", notes: "got first round but too early", spokeTo: "", createdAt: Date.now() },
    { id: "a43", company: "Clover Health", role: "Strategic Initiatives, Clover Care Services", appliedDate: "2026-01-21", method: "Company Website", location: "", verdict: "Withdrew", notes: "got first round but too early", spokeTo: "", createdAt: Date.now() },
    { id: "a44", company: "Courier Health", role: "", appliedDate: "2026-01-21", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a45", company: "Figma", role: "GTM Strategy Mgr", appliedDate: "2026-01-21", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a46", company: "Garner Health", role: "s&O Mgr", appliedDate: "2026-01-21", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a47", company: "Humata Health", role: "GTM Strategy Mgr", appliedDate: "2026-01-21", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a48", company: "Tomorrow Health", role: "Sr Mgr, BizOps", appliedDate: "2026-01-21", method: "Linkedin", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a49", company: "WHOOP", role: "Senior BizOp Mgr", appliedDate: "2026-01-21", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a50", company: "Pinterest", role: "Corp Strat Lead - Product", appliedDate: "2026-01-23", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a51", company: "Runna", role: "Partnerships Lead", appliedDate: "2026-01-23", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a52", company: "Quince", role: "S&O", appliedDate: "2026-01-24", method: "GTS", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a53", company: "Brellium", role: "PM", appliedDate: "2026-01-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a54", company: "CVS", role: "CoS & Ops - Growth Analytics", appliedDate: "2026-01-28", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a55", company: "CVS", role: "Mgr Digital Product Strat", appliedDate: "2026-01-29", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a56", company: "Counsel Health", role: "PM, Consumer", appliedDate: "2026-02-03", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a57", company: "AthenaHealth", role: "Corp Strat & Dev Mgr", appliedDate: "2026-02-19", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a58", company: "LexisNexis", role: "Mgmt Associate", appliedDate: "2026-02-19", method: "GTS", location: "", verdict: "Withdrew", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a59", company: "Sierra AI", role: "Strategist, Agent Dev - Healthcare", appliedDate: "2026-03-09", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a60", company: "Talkiatry", role: "Sr Mg, AI S&O", appliedDate: "2026-03-12", method: "Linkedin", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a61", company: "A Place for Mom", role: "PM, Web", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a62", company: "Alaffia", role: "Senior PM", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a63", company: "ClassDOjo", role: "Monetization Growth PM", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a64", company: "Doordash", role: "PM", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a65", company: "Equity Health", role: "COS", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a66", company: "FLIP", role: "PM", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a67", company: "Hinge Health", role: "BizOps & Strat Mgr", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a68", company: "Meta", role: "Prod Ops Mgr, Ai Operations", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a69", company: "Monogram Health", role: "Client Implementation Opz Mgr", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a70", company: "Mount Sinai Health", role: "Product Owner II", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a71", company: "Mount Sinai Health", role: "Sr Mgr, Product Commercialization", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a72", company: "Mural Health", role: "Manager, GTM S&O", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a73", company: "Navan", role: "GTM S&O Mgr", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a74", company: "Navina", role: "Sr Customer Success Mgr - Digital Health", appliedDate: "2026-03-12", method: "Linkedin", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a75", company: "OpenTable", role: "Sr Mgmr, Global Partnerships", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a76", company: "Oura", role: "Staff PM, Health Risk Detection", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a77", company: "Oura", role: "Senior PM, Heart Health", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a78", company: "Paradigm", role: "Director, Strat & Biz Ops - Healthcare & Clinical Research", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a79", company: "Pearl Health", role: "Senior Mgr, Growth Solutions App", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "got 1st round, but too early (want someone to start in may)", spokeTo: "", createdAt: Date.now() },
    { id: "a80", company: "Salesforce", role: "Pricing Strat, Mgr / Sr Mgr", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a81", company: "Spotify", role: "Associate Director, Monetization Strat", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a82", company: "Spring Health", role: "Director, BizOps & Strat", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a83", company: "Strava", role: "Prod Ops Mgr", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a84", company: "Talkspace", role: "Senior PM, AI", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a85", company: "Virta Health", role: "Snr Chanel Mgmt, DirectMail", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a86", company: "Wayoh", role: "COS", appliedDate: "2026-03-12", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a87", company: "WHOOP", role: "Sr Biz Planning Mgr", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a88", company: "WHOOP", role: "Sr Mgr - Ecomercise - Accessories & Apparel", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a89", company: "Wolters Kluwer", role: "Biz Analytics Mgr - Biz Ops & Strat", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a90", company: "ZocDoc", role: "Senior Associate, Commercial s&O", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a91", company: "Google", role: "S&O Lead", appliedDate: "2026-03-12", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a92", company: "Oscar Health", role: "BizOps Sr Mgr", appliedDate: "2026-03-18", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a93", company: "A Place for Mom", role: "Sr Mgr, Organic Growth Strat", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a94", company: "Clarion", role: "S&O Lead", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a95", company: "Fora", role: "Senior Mgr, Prod Ops", appliedDate: "2026-03-26", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a96", company: "Headway", role: "SR PM Acquisition (Provider)", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a97", company: "Meta", role: "BizDev Mgr, AI Partnerships", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a98", company: "Mochi Health", role: "CoS", appliedDate: "2026-03-26", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a99", company: "Ophelia", role: "Senior PM", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a100", company: "Oshi", role: "Sr Mgmr Partnerships S&O", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a101", company: "Pomelo", role: "Senior Mgr, Growth", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a102", company: "Samsung", role: "Mgr - AI S&O", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a103", company: "Stedi", role: "BizOps & Strat", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a104", company: "Uber", role: "Strategy Lead, Global Membership", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a105", company: "Adobe", role: "senior Pricing Ops Mgr", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Opening", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a106", company: "Blink Health", role: "Sr PM", appliedDate: "2026-03-27", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a107", company: "Charlie Health", role: "PM - Therapist Success", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a108", company: "ClassPass", role: "Senior PM, Consumer Growth", appliedDate: "2026-03-27", method: "Linkedin", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a109", company: "CVS", role: "Manger - Strategic Marketing & Team Engagement -  Healthcare Analytics", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Opening", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a110", company: "CVS", role: "Senior Associate - CVS Health Ventures", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a111", company: "CVS", role: "Associate, CVS Health Ventures Market Dev", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a112", company: "Distyl AI", role: "Product Strategist, Healthcare Solutions", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a113", company: "Fay", role: "BizOps", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a114", company: "Hello Heart", role: "CoS", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a115", company: "Hopper", role: "Sr Mgr - Revenue Ops - Travel Supply & Ai", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "Rejected 3/30", spokeTo: "", createdAt: Date.now() },
    { id: "a116", company: "Included health", role: "CoS to CEO", appliedDate: "2026-03-27", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a117", company: "Komodo Health", role: "Senior AI Engagement Mgr", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a118", company: "Maven Clinic", role: "PM, Eligibility & Enrollments", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a119", company: "Maven Clinic", role: "CoS, Product & Ops", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a120", company: "McKinsey", role: "PM I- Life Sciences", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a121", company: "Microsoft", role: "Director, AI S&O Program Manager", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a122", company: "Noom", role: "Senior PM", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a123", company: "Notion", role: "Partner S&O Manager", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a124", company: "Notion", role: "Product Operations Mgr", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a125", company: "NVIDIA", role: "GTM Program Manager, Healthcare & Life Sciences", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a126", company: "Odyssey", role: "Senior PM - Growth & Program Ops", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a127", company: "Omada Health", role: "Program Mgr, S&O", appliedDate: "2026-03-27", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a128", company: "OpenAI", role: "Growth , Biz Strat & Ops", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a129", company: "Oura", role: "Director, Corp Strat", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a130", company: "Oura", role: "Senior BizOp Mgr", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a131", company: "Oura", role: "Senior BizOps Program Mgr", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a132", company: "Pareto Health", role: "Senior Mgr, Growth Strat", appliedDate: "2026-03-27", method: "Linkedin", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a133", company: "Playlist", role: "Senior PM, Consumer Growth", appliedDate: "2026-03-27", method: "Linkedin", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a134", company: "Samsung", role: "Sr Mgr - Product Strat", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a135", company: "Samsung", role: "Sr Mg - Global Partnerships & BizDev (digital Health)", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a136", company: "Samsung", role: "Sr Mgr, Product Strat (Digital Health)", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a137", company: "SOL Mental Health", role: "COS", appliedDate: "2026-03-27", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a138", company: "Spring Health", role: "Sr Mgr, Clinical S&O", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a139", company: "Strava", role: "Senior Biz Analyst", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a140", company: "Sutter Health", role: "Innovation Strategist, Design & Innovation", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a141", company: "Synapse Health", role: "CoS", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a142", company: "Tandem", role: "S&O Lead", appliedDate: "2026-03-27", method: "Referral", location: "", verdict: "In Process", notes: "Referrer: Madison Mok. First round - 4/2", spokeTo: "", createdAt: Date.now() },
    { id: "a143", company: "Tempus", role: "PM", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a144", company: "TikTok", role: "Product S&O Mgr, Acquisition Gorwth", appliedDate: "2026-03-27", method: "Linkedin", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a145", company: "Visa", role: "Sr Mgr - Visa Ventures", appliedDate: "2026-03-27", method: "GTS", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a146", company: "Google", role: "S&O Senior Associate", appliedDate: "2026-03-27", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a147", company: "Abridge", role: "Product Ops Mgr", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a148", company: "Atlas", role: "COS", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a149", company: "BetterUp", role: "Principal BizOps Mgr", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a150", company: "Blossom H ealth", role: "Founding Partnerships Lead", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a151", company: "Charlie Health", role: "Director of Care Strat", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a152", company: "Commure", role: "CoS", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a153", company: "Duet", role: "Founding Payer Partnerships Lead", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a154", company: "Exacare AI", role: "PM", appliedDate: "2026-03-28", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a155", company: "Google", role: "S&O Mgr, GTM", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a156", company: "Granted", role: "Agent PM", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "In Process", notes: "first round - 4/13", spokeTo: "", createdAt: Date.now() },
    { id: "a157", company: "Machinify", role: "COS to CTO", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a158", company: "Nourish", role: "S&O Associate / lead", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a159", company: "Oscar Health", role: "BizOps Sr Mgr", appliedDate: "2026-03-28", method: "", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a160", company: "Pivotal Health", role: "Head of Partnerships", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a161", company: "Prosper Health", role: "S&O Lead", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a162", company: "Qualified Health", role: "PM", appliedDate: "2026-03-28", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a163", company: "Quizlet", role: "Product Ops Program Mgr", appliedDate: "2026-03-28", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a164", company: "Roivant", role: "Eir, VBC", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a165", company: "Savant Bio", role: "Director, Strategic Partnerships", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a166", company: "Scale AI", role: "BizOps & Strat Mgr", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a167", company: "Sprinter Health", role: "Clinical Strat Manager", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "In Process", notes: "1st round -", spokeTo: "", createdAt: Date.now() },
    { id: "a168", company: "Sprinter Health", role: "S&O, Market Strategist (GTM & Expansion)", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a169", company: "Talkspace", role: "Sr PM, Growth", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a170", company: "Thesis Care", role: "CoS", appliedDate: "2026-03-28", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a171", company: "Thyme Care", role: "Sr Mgr, Member Operations", appliedDate: "2026-03-28", method: "", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a172", company: "Twitch", role: "Sr Mgr, S&O", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a173", company: "VideaHealth", role: "Sr Mgr of Channel Partnerships", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a174", company: "Whoop", role: "Sr Mgr, Corp Strat", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a175", company: "Whoop", role: "PM II, Healthcare", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a176", company: "Blink Health", role: "Manager, Network Strat and partner operations", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "In Process", notes: "first round interview (notified 3/31)", spokeTo: "", createdAt: Date.now() },
    { id: "a177", company: "CVS", role: "Sr Manager, Clinical Innovation", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a178", company: "CVS", role: "Manager, Pharma Innovation", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a179", company: "CVS", role: "CoS, Caremark Digital Tech", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a180", company: "CVS", role: "Senior Biz Consultant Mgr, Dental & Vision", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a181", company: "CVS", role: "Sr Mgr, Solutions Delivery", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a182", company: "CVS", role: "Manager, Platform Strategy", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a183", company: "CVS", role: "PM - AI", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a184", company: "CVS", role: "Senior PM - Payer Analytics", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a185", company: "CVS", role: "Senior PM - Payer Analytics", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a186", company: "Daymark Health", role: "", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a187", company: "Fora", role: "Senior Mgr / Mgr, Central S&O", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a188", company: "Harper", role: "Special Projects Lead", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a189", company: "Sierra AI", role: "Rev Ops, Central Ops Manager", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a190", company: "Sierra AI", role: "Pricing s&o", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a191", company: "Workable", role: "Senior Manager, Clinical S&O", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a192", company: "Eight Sleep", role: "Business Operations Manager", appliedDate: "2026-03-30", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a193", company: "Boulder Care", role: "COS", appliedDate: "2026", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a194", company: "CapitalOne", role: "Product Manager", appliedDate: "2026", method: "Company Website", location: "VA, DC, IL, NYC", verdict: "Rejected - interviewed", notes: "online assessment", spokeTo: "", createdAt: Date.now() },
    { id: "a195", company: "Cedar", role: "Product S&O, Strategist III", appliedDate: "2026", method: "Linkedin", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a196", company: "Eight Sleep", role: "Product Manager", appliedDate: "2026", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a197", company: "Included health", role: "Sr Mgr, Biz Acceleration - All Included Care & Navigation", appliedDate: "2026", method: "Linkedin", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a198", company: "Kimber Health", role: "CoS", appliedDate: "2026", method: "Company Website", location: "", verdict: "Rejected - interviewed", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a199", company: "Spring Health", role: "Director, BizOps & Strat", appliedDate: "2026", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a200", company: "Talkiatry", role: "Sr Mgr, BizOps", appliedDate: "2026", method: "Linkedin", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a201", company: "Talkiatry", role: "Sr Mgr, Growth S&O", appliedDate: "2026", method: "Linkedin", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a202", company: "Tomorrow Health", role: "PM, New Ventures", appliedDate: "2026", method: "Linkedin", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a203", company: "Aligned Marketplace", role: "Clinical Growth & Ops", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "1st round interview 4/14", spokeTo: "", createdAt: Date.now() },
    { id: "a204", company: "Mochi Health", role: "Operations Associate - Strategy", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "In Process", notes: "1st round interview", spokeTo: "", createdAt: Date.now() },
    { id: "a205", company: "Fira Health", role: "Special Projects Lead", appliedDate: "2026-03-30", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a206", company: "Sailor Health", role: "S&O Lead / Associate", appliedDate: "2026-03-16", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a207", company: "Predoc", role: "Sr Mgr, Clinical S&O", appliedDate: "2026-03-29", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a208", company: "Fora", role: "Sr Mgr, Prod Ops", appliedDate: "2026-03-26", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a209", company: "Arlo", role: "CoS", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a210", company: "Smarter Technologies", role: "AI Product Strat and analytics associate", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a211", company: "Doctronic", role: "PM, Telehealth", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a212", company: "Givers", role: "Sr Mgr, Strategic Ops", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "Rejected without Interview", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a213", company: "Silna", role: "Operations", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a214", company: "m7 Health", role: "S&O", appliedDate: "2026-03-28", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a215", company: "Hinge Health", role: "BizOps & Strat Mgr", appliedDate: "2026-03-16", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a216", company: "Adaptive/ Fira Health", role: "Special Projects Lead", appliedDate: "2026-03-30", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a217", company: "Equality Health", role: "CoS", appliedDate: "2026-03-16", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a218", company: "Clover Health", role: "BizOps & Strat Mgr", appliedDate: "2026-03-30", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a219", company: "Clover Health", role: "Special Projects Lead - Office of CEO", appliedDate: "2026-03-30", method: "Company Website", location: "", verdict: "In Process", notes: "1st round interview", spokeTo: "", createdAt: Date.now() },
    { id: "a220", company: "Genentech", role: "Director, Strategy & BizOps", appliedDate: "2026-03-31", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a221", company: "Genentech", role: "Senior/Principal Business Manager- Translational Medicine", appliedDate: "2026-03-31", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a222", company: "Genentech", role: "Senior Product Manager", appliedDate: "2026-03-31", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a223", company: "Beli", role: "Biz Dev Lead", appliedDate: "2026-03-31", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a224", company: "Beli", role: "Growth Lead", appliedDate: "2026-03-31", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a225", company: "Cisco", role: "S&O Manager", appliedDate: "2026-04-02", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a226", company: "CVS", role: "Senior Manager, Strategy & Innovation", appliedDate: "2026-04-03", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a227", company: "CVS", role: "Sr Mgr - Biz Strat - Pharmaceutical Contracting & Purchasing", appliedDate: "2026-04-03", method: "Company Website", location: "", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a228", company: "TikTok", role: "Product Manager, Shop Advertiser Experience - Global Monetization Product and Technology - San Jose", appliedDate: "2026-04-03", method: "Linkedin", location: "San Jose, CA", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a229", company: "TikTok", role: "Product Strategy & Operations Manager - Informative Content Growth", appliedDate: "2026-04-03", method: "Linkedin", location: "San Jose, CA", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a230", company: "TikTok", role: "Business Analyst, Monetization", appliedDate: "2026-04-03", method: "Linkedin", location: "San Jose, CA", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() },
    { id: "a231", company: "TikTok", role: "TikTok Shop - Strategy & Operations Manager", appliedDate: "2026-04-03", method: "Linkedin", location: "NYC", verdict: "No Update", notes: "", spokeTo: "", createdAt: Date.now() }
  ],

  savedPositions: [
    { id: "sp1", company: "Stripe", role: "Product Manager", method: "LinkedIn", url: "", notes: "Saw on LinkedIn, looks like a good fit", deadline: "2026-04-20", createdAt: Date.now() - 86400000 * 2 },
    { id: "sp2", company: "Figma", role: "Associate PM", method: "Referral", url: "", notes: "Referral from classmate", deadline: "", createdAt: Date.now() - 86400000 },
    { id: "sp3", company: "Notion", role: "Product Manager, Growth", method: "Company Website", url: "", notes: "", deadline: "2026-04-15", createdAt: Date.now() },
  ],
};
